[workspace]
members = [
    "atproto-repo",
    "skylight-followsdb",
    "skylight-followsdb-crawler",
    "skylight-followsdb-crawlstatus",
    "skylight-followsdb-ingester",
    "skylight-plcdb",
    "skylight-plcdb-ingester",
    "skylight-queryserver",
]
