[workspace]
members = [
    "atproto-repo",
    "skylight-crawler",
    "skylight-followsdb",
    "skylight-followsdb-csvimporter",
    "skylight-ingester",
    "skylight-plcdb",
    "skylight-plcdb-mirrorer",
]
